version: "3.8"
services:
  react-app:
    image: memory-game:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    networks:
      - mynet

networks:
  mynet: